### ISSUE TITLE
custom css?

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud.flexdashboard#16]
Flexdashboard has the ability to load custom css from its YAML header:

```yaml
---
title: "Custom CSS"
output: 
  flexdashboard::flex_dashboard:
    css: styles.css
---
```
http://rmarkdown.rstudio.com/flexdashboard/using.html#css_styles

It would be really cool if we could figure out how to load that css from the notebook. Or, a little bit hackier but also useful, we could enable `rcloud-*.css` assets the way we do for view mode.
